export const FORCAST_WEATHER_ACTIONS = {
    FORCAST_WEATHER_REQUEST: "FORCAST_DATA_REQUEST",
    FORCAST_WEATHER_ERROR: "FORCAST_DATA_ERROR",
    FORCAST_WEATHER_SUCCESS: "FORCAST_DATA_SUCCESS",
  };